# Site settings
title: "Ajay Singh"
description: > 
  Software Developer 

author: Ajay Singh
email: hello@ajaysingh.me
threads_url: "https://www.threads.com/@aj_ysingh"
github_username: ajaydeepsingh

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ajaysingh.me" # the base hostname & protocol for your site

# Google Analytics 4 Measurement ID (for example, G-XXXXXXXXXX).
# Leave blank to disable analytics.
google_analytics_measurement_id: "G-C796FQYM2D"
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title

sass:
    style: compressed

exclude: [vendor]
